version: "3.1"
services:
  mysql:
    build: ./mysql
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: url_tester
      MYSQL_USER: tohid
      MYSQL_PASSWORD: 123456
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080